#!/usr/bin/env bash
set -e

NODE=<%= node.name.e %>
PROVIDER=<%= node.provider.name.e %>
ZONE=<%= node.zone.e %>
ROLES=<%= node.build_order.map(&:name).join(' ').e %>
CREATED_AT=<%= Time.now.to_s.e %>
SIZE=<%= node.size.e %>
IMAGE=<%= node.image.e %>
IPV4_PUBLIC=<%= node.ipv4_public.e %>
IPV4_PRIVATE=<%= node.ipv4_private.e %>

LEADER_FILE=~cult/cult/leader-of

colorize() {
  i=124
  d=1
  while IFS='' read -r LINE ; do
    printf "\e[38;5;${i}m$LINE\e[0m\n"
    i=$(($i + $d))
    if [ $i -eq 124 ] ; then
      d=1
    elif [ $i -eq 135 ] ; then
      d=-1
    fi
  done
}

inf() {
  TEXT=$(echo "$1" | fold -s -w 78 | fmt -s -c -w 78)
  printf '\e[38;5;8m%s\e[0m\n' "$TEXT"
}

# We don't want everyone to have to install figlet.
cat - <<EOD | colorize

                     @@@@@@@  @@@  @@@  @@@       @@@@@@@
                    @@@@@@@@  @@@  @@@  @@@       @@@@@@@
                    !@@       @@!  @@@  @@!         @@!
                    !@!       !@!  @!@  !@!         !@!
                    !@!       @!@  !@!  @!!         @!!
                    !!!       !@!  !!!  !!!         !!!
                    :!!       !!:  !!!  !!:         !!:
                    :!:       :!:  !:!   :!:        :!:
                     ::: :::  ::::: ::   :: ::::     ::
                     :: :: :   : :  :   : :: : :     :


EOD

inf "node: $NODE@$PROVIDER/$ZONE:$SIZE/$IMAGE"
inf "addr: $IPV4_PUBLIC, $IPV4_PRIVATE"
inf "created: $CREATED_AT"
inf "roles: $ROLES"
[ -f "$LEADER_FILE" ] && inf "zone leader: $(cat "$LEADER_FILE")"
echo
