#!/usr/bin/env bash
set -e

sudo ufw-delete-by-comment 'postgres-client:'

<%
  pgpools = node.zone_peers.with(role: 'postgres-pgpool')
  servers = node.zone_peers.with(role: 'postgres-server')
  upstreams = pgpools.empty? ? servers : pgpools
%>


<% upstreams.each do |other| %>
  sudo ufw allow out to <%= other.addr_from(node).q %> \
                     port 5432 \
                     from <%= node.addr_from(other).q %> \
                     comment 'postgres-client: accessing <%= other.name.q %>'
<% end %>
