#!/usr/bin/env bash
set -e

sudo ufw-delete-by-comment 'glusterfs-client:'

<% node.zone_peers.with(role: 'glusterfs-server').each do |other| %>
  sudo ufw allow out to <%= other.addr_from(node).q %> \
                     proto tcp \
                     port 24007,24008,49152,49153 \
                     from <%= node.addr_from(other).q %> \
                     comment 'glusterfs-client: accessing <%= other.name.q %>'
<% end %>
