#!/usr/bin/env bash
set -e

<% leader = node.zone_leader('glusterfs-server') %>

if ! cat /etc/group | cut -d: -f1 | grep -q gluster-access ; then
  sudo addgroup gluster-access
fi

if [ ! -d /data ] ; then
  sudo mkdir -p /data
fi

# Rewrite fstab entry
cat /etc/fstab | grep -v glusterfs > /tmp/fstab-without-glusterfs

cat <<FSTAB | tee -a /tmp/fstab-without-glusterfs > /dev/null
<%= leader.addr_from(node) %>:/pool /data glusterfs defaults,_netdev 0 0
FSTAB

sudo mv /tmp/fstab-without-glusterfs /etc/fstab

if ! mount | grep ' on /data ' ; then
  sudo mount /data
fi
