#!/usr/bin/env bash
set -e

<% leader = node.zone_leader('glusterfs-server') %>

[ -d /data ] || sudo mkdir /data

# Remove existing glusterfs mounts from fstab
cat /etc/fstab | grep -v glusterfs > /tmp/fstab-without-glusterfs

cat <<FSTAB | tee -a /tmp/fstab-without-glusterfs > /dev/null
<%= leader.addr_from(node) %>:/pool /data glusterfs defaults,_netdev 0 0
FSTAB

sudo mv /tmp/fstab-without-glusterfs /etc/fstab

sudo mount | grep -q ' on /data ' || sudo mount /data
