#!/usr/bin/env bash
set -e

sudo mkdir -p /etc/ssl/metermd
sudo cp files/metermd-ca.crt /etc/ssl/metermd

sudo ln -s /etc/ssl/metermd/metermd-ca.crt /usr/local/share/ca-certificates/

sudo update-ca-certificates
