#!/usr/bin/env bash
set -e

echo 'IPV6=yes' | sudo tee -a /etc/default/ufw

sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default deny outgoing

sudo ufw allow in ssh
sudo ufw allow out domain   # AKA DNS
sudo ufw allow out http     # Ubuntu packages
sudo ufw allow out https    # Ubuntu packages
sudo ufw allow out git      # For gems, etc

sudo ufw --force enable
