#!/usr/bin/env bash
set -e

# This is a meta-role.  A role depending on 'rvm' gets the installer installed.
# Additionally, a role can symlink this file into their task directory to
# actually have it installed with parameters they can set on their role.

<% if role.name == 'rvm' %>
  sudo mkdir -p /usr/local/share/rvm-installer
  sudo cp files/rvm.{sh,asc} /usr/local/share/rvm-installer/
  sudo chmod +x /usr/local/share/rvm-installer/rvm.sh
<% else %>

  # If the we specified a user, re-exec this script as that user
  <% if (rvm_user = node.definition['rvm_user']) %>
    [[ "$USER" == <%= rvm_user.e %> ]] || \
      exec sudo -H -u <%= rvm_user.e %> -- "$0" "$@"
  <% end %>

  gpg --import /usr/local/share/rvm-installer/rvm.asc
  bash /usr/local/share/rvm-installer/rvm.sh

  <% if (rvm_use = node.definition['rvm_ruby']) %>
    hash -r
    source "$HOME/.rvm/scripts/rvm"
    rvm install <%= rvm_use.e %>
    rvm use <%= rvm_use.e %> --default
  <% end %>
<% end %>
