#!/usr/bin/env bash
set -e

sudo adduser --disabled-password \
             --gecos 'meter.md app server' \
             metermd

echo 'metermd ALL=NOPASSWD: /usr/bin/apt-get' | sudo tee /etc/sudoers.d/metermd
