#!/usr/bin/env bash

cat <<BASH | sudo -i -u metermd bash -s
  gpg --keyserver hkp://keys.gnupg.net \
      --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  curl -sSL https://get.rvm.io | bash -s
BASH

cat <<BASH | sudo -i -u metermd bash -s
  rvm get head
  rvm install ruby-2.3
  rvm use ruby-2.3 --default
BASH
