#!/usr/bin/env bash
set -e

URL="https://packages.graylog2.org/repo/packages/graylog-2.0-repository_latest.deb"
DEB=files/graylog-2.0-repository_latest.deb

if [ ! -f "$DEB" ] ; then
  curl -L -o "$DEB" "$URL"
fi

sudo apt-get -yqq install default-jre-headless
sudo dpkg -i "$DEB"
sudo apt-get update
sudo apt-get -yqq install graylog-server
