#!/usr/bin/env bash
set -e

cat <<APT | sudo tee /etc/apt/sources.list.d/glusterfs-ppa.list > /dev/null
deb http://ppa.launchpad.net/gluster/glusterfs-3.8/ubuntu $(lsb_release -sc) main
APT

sudo apt-get update
