#!/usr/bin/env bash
set -e

RUNLEVEL=1 sudo -E apt-get -yqq install hitch

# We don't want the system-level hitch with hitch.conf...
sudo systemctl disable hitch

# Installing this service file lets us launch e.g., hitch@redis.service to use
# redis.conf
sudo cp 'files/hitch@.service' '/etc/systemd/system/'
