#!/usr/bin/env bash
set -e
shopt -s nullglob

DB_VOLUME=/mnt/db*

if [ ! -d "$DB_VOLUME" ]; then
  echo "No attached DB_VOLUME to use."
  exit 0
fi

# move the normal install aside, and link to the external disk.
sudo mv '/var/lib/postgresql' '/var/lib/postgresql-debian'
sudo ln -s "$DB_VOLUME/postgresql" '/var/lib'

sudo mv '/etc/postgresql' '/etc/postgresql-debian'
sudo ln -s "$DB_VOLUME/postgresql/etc" "/etc/postgresql"

sudo mv '/etc/postgresql-common' '/etc/postgresql-common-debian'
sudo ln -s "$DB_VOLUME/postgresql/etc-common" "/etc/postgresql-common"
