#!/usr/bin/env bash
set -e

sudo gpasswd -a cult ssl-cert

sudo cp files/postgres-{server,replication}.{crt,key} /etc/ssl/metermd/

sudo chown root:ssl-cert /etc/ssl/metermd/postgres-{server,replication}.{crt,key}
sudo chmod ug=r,o= /etc/ssl/metermd/postgres-{server,replication}.key
