#!/usr/bin/env bash
set -e

PGETC=/etc/postgresql/<%= node.definition['pg_version'] %>/main

# Note: we accept connections from anyone, but in practice:
# the listen address is just on the smaller "sortranet".
cat - <<PG_HBA | sudo tee -a "$PGETC/pg_hba.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
hostssl  all          all          255.255.255.255/0  cert clientcert=1 map=cert
hostssl  all          all          ::1/0              cert clientcert=1 map=cert

# Allow replication using the same cert
hostssl  replication  replication  255.255.255.255/0  cert clientcert=1 map=cert
hostssl  replication  replication  ::1/0              cert clientcert=1 map=cert
PG_HBA

cat - <<PG_IDENT | sudo tee -a "$PGETC/pg_ident.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
#
# Keep in mind: pgpool represents itself as postgres-server because it has to
# use the same key for clients and servers (it also has our key!)
#
cert             /postgres\-(client|server) metermd
cert             /postgres\-(client|server) postgres
cert             postgres-replication       replication
PG_IDENT

# Comment out any SSL settings
sudo sed -i.bak -e 's/^ssl/#ssl/;' "$PGETC/postgresql.conf"
<%
  listen_addresses = ['localhost', node.ipv4_private, node.ipv6_private].compact.join(',')
%>

cat - <<PG_CONF | sudo tee -a "$PGETC/postgresql.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
listen_addresses = '*'
ssl = true
ssl_ca_file   = '/etc/ssl/metermd/metermd-ca.crt'
ssl_cert_file = '/etc/ssl/metermd/postgres-server.crt'
ssl_key_file  = '/etc/ssl/metermd/postgres-server.key'

ssl_ciphers = 'EECDH+AESGCM'
ssl_prefer_server_ciphers = on
ssl_ecdh_curve = 'prime256v1'

# Static, many overwritten in dynamic.conf
max_connections = 300
max_wal_senders = 100
wal_level = logical
wal_keep_segments = 32
wal_sender_timeout = 15s
wal_receiver_timeout = 60s
max_standby_streaming_delay = 30s
max_standby_archive_delay = 60s
hot_standby = on
hot_standby_feedback = on

include '$PGETC/dynamic.conf'
PG_CONF

cat - <<DYNAMIC_CONF | sudo tee -a "$PGETC/dynamic.conf"
# Placeholder file for sync updates.
DYNAMIC_CONF
