#!/usr/bin/env bash
set -e

[[ "$USER" == "postgres" ]] || exec sudo -H -u postgres -- "$0" "$@"

source pg-auth -k postgres-server
cat - <<SQL | psql
  CREATE ROLE replication WITH REPLICATION LOGIN;
  CREATE ROLE backup WITH REPLICATION SUPERUSER LOGIN;
  CREATE DATABASE test OWNER postgres;
SQL
