#!/usr/bin/env bash
set -e

[[ "$USER" == "postgres" ]] || exec sudo -H -u postgres -- "$0" "$@"

ETCPG=/etc/postgresql/<%= node.definition['pg_version']%>/main

source pg-auth postgres-server
cat - <<SQL | psql
  CREATE ROLE metermd WITH SUPERUSER LOGIN;
  CREATE ROLE replication WITH REPLICATION LOGIN;

  CREATE DATABASE test OWNER metermd;
SQL
