#!/usr/bin/env bash
set -e

[[ "$USER" == "postgres" ]] || exec sudo -H -u postgres -- "$0" "$@"

source pg-auth postgres-server
cat - <<SQL | psql
  CREATE ROLE replication WITH REPLICATION LOGIN;

  CREATE ROLE metermd WITH SUPERUSER LOGIN;
  CREATE DATABASE test OWNER metermd;
SQL
