#!/usr/bin/env bash
set -e

sudo ufw-delete-by-comment 'postgres-server:'

<% node.zone_peers.with(role: /^postgres\-/).each do |other| %>
  sudo ufw allow in to <%= node.addr_from(other).q %> \
                    port 5432 \
                    from <%= other.addr_from(node).q %> \
                    comment 'postgres-server: servicing <%= other.name.q %>'
<% end %>
