#!/usr/bin/env bash
set -e

<%
  master = node.zone_leader(role)
  slaves = master.zone_peers.with(role: role)
%>

<% if node == master %>
  echo '<%= node.name %>: i am the master'
<% else %>
  echo '<%= node.name %>: i am a slave'
  source pg-auth
  echo pg_basebackup --xlog \
                     --pgdata /home/cult/basebackup \
                     --username metermd \
                     --no-password \
                     --host <%= master.addr_from(node).q %>
<% end %>
