#!/usr/bin/env bash
set -e

# This script deletes all UFW rules with a comment matching the first argument.
# Note that it does a prefix match, so you can use the rest of the comment for
# real purposes.

fail() {
  echo "$0: $1" >&2
  exit 1
}

[ ! -z "$1" ] || fail "usage: $0 COMMENT-PREFIX"

delete_rule() {
  while IFS='' read -r LINE ; do
    NUMBER=$(echo "$LINE" | cut -d']' -f 1 | tr -d '[] ')
    echo 'y' | ufw delete "$NUMBER" > /dev/null
  done
}

ufw status numbered | grep -F "# $1" | tac | delete_rule
