#!/usr/bin/env bash
set -e

# Start from a clean slate
sudo ufw-delete-by-comment 'glusterfs-server:'

<% ports = '24007:24017,49151:49161' %>

<% node.zone_peers.with(role: /^glusterfs/).each do |other| %>
  sudo ufw allow in to <%= node.addr_from(other).e %> \
                    proto tcp \
                    port <%= ports %> \
                    from <%= other.addr_from(node).e %> \
                    comment 'glusterfs-server: servicing <%= other.name.dq %>'

  sudo ufw allow out to <%= other.addr_from(node).e %> \
                    proto tcp \
                    port <%= ports %> \
                    from <%= node.addr_from(other).e %> \
                    comment 'glusterfs-server: accessing <%= other.name.dq %>'
<% end %>
