#!/usr/bin/env bash
set -e

# We keep our volume pool in /pool, but that's really just a symlink to
# /mnt/pool-[0-9], which was mounted in base sync
if [ ! -d /pool ]; then
  MOUNTED=$(find /mnt -maxdepth 1 -type d -name 'pool-*' | head -n 1)
  if [ ! -z "$MOUNTED" ]; then
    sudo ln -s "$MOUNTED" /pool
  else
    sudo mkdir /pool
  fi
fi
