#!/usr/bin/env bash
# set -e

<% peers = node.zone_peers.with(role: 'glusterfs-server') %>

<% if node.zone_leader?('glusterfs-server') %>
  <% peers.each do |o| %>
    sudo gluster peer probe <%= o.addr_from(node).q %> || true
  <% end %>
<% end %>
