#!/usr/bin/env bash
set -e

if [ ! -d /pool ]; then
  MOUNTED=$(find /mnt -maxdepth 1 -type d -name 'pool-*' | head -n 1)
  if [ ! -z "$MOUNTED" ]; then
    sudo ln -s "$MOUNTED" /pool
  else
    sudo mkdir /pool
  fi
fi
