#!/usr/bin/env bash
# set -e

REPLICA=2

<%
  peers = node.zone_peers.with(role: 'glusterfs-server')
  cluster = [node] + peers

  peer_uris = cluster.map do |o|
    "#{o.addr_from(node)}:/pool"
  end.join(" ")

  leader = node.zone_leader('glusterfs-server')
%>

bricklist() {
  sudo gluster volume status pool | grep '^Brick' | \
           cut -d' ' -f 2 | cut -d':' -f 1 | sort | uniq
}

goal() {
  read -r -d '' GOAL <<'EOD'
  <% cluster.each do |n| %>
    <%= n.addr_from(node) %>
  <% end %>
EOD

  echo "$GOAL" | sed -e 's/^[ ]*//'| sort | uniq
}

additions() {
  (echo "$(bricklist)"; echo "$(goal)") | sort | uniq -u
}

removals() {
  diff <(bricklist | sort) <(goal | sort) | grep '^<' | sed -e 's/^..//'
}

echo Bricklist: $(bricklist)
echo Goal: $(goal)
echo Additions: $(additions)
echo Removals: $(removals)
exit 0

<% if node.zone_leader?('glusterfs-server') %>
  echo "Performing leader actions..."

  STATUS=$(sudo gluster volume status pool 2>&1)
  echo "STATUS=$STATUS"
  if echo "$STATUS" | grep -q "does not exist" ; then
    echo "Creating volume"
    sudo gluster volume create pool replica "$REPLICA" <%= peer_uris %> force
    sudo gluster volume set pool client.ssl on
    sudo gluster volume set pool server.ssl on
    sudo gluster volume set pool auth.ssl-allow 'gluster-client,gluster-server'
    sudo gluster volume set pool ssl.cipher-list 'EECDH+AESGCM:AES256+EECDH'
  else
    EXISTING=$(sudo gluster volume status pool | grep '^Brick' | \
               cut -d' ' -f 2 | cut -d':' -f 1)
    EXISTING_COUNT=$(echo "$EXISTING" | wc -l)
    <% peers.each do |peer| %>
      ADDITIONS=""
      PEER=<%= peer.name.q %>
      PEER_IP=<%= peer.addr_from(node).q %>
      if echo "$EXISTING" | grep "^$PEER_IP\$" ; then
        echo "Skipping peer: $PEER ($PEER_IP), already in set"
      else
        echo "Adding peer: $PEER ($PEER_IP)"
        ADDITIONS="$ADDITIONS $PEER_IP:/pool"
      fi

      echo "Additions: $ADDITIONS"
    <% end %>

    ADDITION_COUNT=$(echo "$ADDITIONS" | wc -w)
    REMAINDER=$(($ADDITION_COUNT % $REPLICA))
    if [ "$REMAINDER" -ne "0" ]; then
      echo "Not a multiple of replica, pruning tail"
      BEST=$(( ( $REMAINDER / $REPLICA ) * $REPLICA ))
      ADDITIONS=$(echo "$ADDITIONS" | xargs -n 1 echo | cat | \
                                      head -n $BEST | tr '\n' ' ')

    fi
    ADDITIONS=$(echo $ADDITIONS)

    if [ ! -z "$ADDITIONS" ]; then
      puts "Activating additions: $ADDITIONS"
      sudo gluster volume add-brick pool replica "$REPLICA" $ADDITIONS
    fi
  fi

  STATUS=$(sudo gluster volume status pool 2>&1)
  if echo "$STATUS" | grep -q "is not started" ; then
    echo "starting cluster"
    sudo gluster volume start pool
  fi
  exit 0
<% end %>
