#!/usr/bin/env bash
set -e

# Note: This is a shared task mean to be symlinked from dependent tasks

sudo ln -s /etc/ssl/metermd/metermd-ca.crt /etc/ssl/glusterfs.ca
sudo touch /var/lib/glusterd/secure-access
