#!/usr/bin/env bash
set -e

<% %w(ipv4_private ipv6_private).each do |key| %>
  <% if (addr = node.definition[key]) %>

    for PORT in 111 24007 24008 49152 49153 ; do
      sudo ufw allow in to <%= addr.q %> port "$PORT"
    done

  <% end %>
<% end %>
