#!/usr/bin/env bash
set -e

echo 'IPV6=yes' | sudo tee -a /etc/default/ufw > /dev/null

sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default deny outgoing

sudo ufw allow in ssh comment 'base'      # Cult control
sudo ufw allow out domain comment 'base'  # AKA DNS
sudo ufw allow out http comment 'base'    # Ubuntu packages
sudo ufw allow out https comment 'base'   # Ubuntu packages
sudo ufw allow out git comment 'base'     # For gems, etc

sudo ufw --force enable
