#!/usr/bin/env bash
set -e

wait_for() {
  while :; do
    RUNNING=""
    for i in "$@" ; do
      pgrep "$i" && RUNNING="$i $RUNNING"
    done

    [ -z "$RUNNING" ] && break
    echo "waiting for processes to end: $RUNNING"
    sleep 1
  done
}

wait_for unattended-upgrades
