#!/usr/bin/env bash
set -e

sudo mkdir -p /etc/ssl/metermd

# Install it in our custom store.
sudo cp files/meter.md_Certificate_Authority.crt /etc/ssl/metermd

# Give us a friendly name.
sudo ln -s /etc/ssl/metermd/meter.md_Certificate_Authority.crt \
           /etc/ssl/metermd/metermd-ca.crt

# Add it to the system trust store
sudo ln -s /etc/ssl/metermd/meter.md_Certificate_Authority.crt \
           /usr/local/share/ca-certificates/
sudo update-ca-certificates

# dhparams do not have to be secret nor per-use.  We just need to know that the
# NSA hasn't been cranking on ours for years, which would be the case with
# anything that ships by default with anything.
sudo cp files/dhparam /etc/ssl/metermd/dhparam
