#!/usr/bin/env bash
set -e

# This file generates a map of all hosts on each node in /etc/hosts.  Because
# it's included in `base`, it'll be executed before your custom roles' sync
# tasks.  That means you can parse the map instead of using custom Ruby
# templating, if that's not your thing.
#
# The output format is:
#
# 192.168.1.1 node-name # cult: base *role1 role2 role3
#
# Where the * signifies that the node is the zone leader of that role.

CULTMAP="$HOME/cult/hosts"
mkdir -p $(basename "$CULTMAP")
sudo rm -f "$CULTMAP"

cat - <<HOSTS | tee "$CULTMAP" > /dev/null
# cult: generated host map from <%= __FILE__ %>
<% nodes.each do |n| %>
<%
  role_string = n.build_order.reject(&:node?).map do |r|
    (n.zone_leader?(r) ? '*' : '') + r.name
  end.join(' ')

  additional_names = n.build_order.reject(&:node?).map do |r|
    n.zone_leader?(r) ? "#{r.name}-ZL" : nil
  end.compact.join(" ")
%>
<%= n.addr_from(node) %> <%= n.name %> <%= additional_names %> # cult: <%= role_string %>
<% end %>
HOSTS

NEW_ETC_HOSTS=$(cat /etc/hosts | grep -v '# cult: '; cat "$CULTMAP")
echo "$NEW_ETC_HOSTS" | sudo tee /etc/hosts > /dev/null
