#!/usr/bin/env bash

# This works with the following client:
# redis = Redis.new(
#   url: 'rediss://somehost/',
#   ssl_params: {
#     ca_file: '/etc/ssl/metermd/metermd-ca.crt',
#     cert: OpenSSL::X509::Certificate.new(File.read('/etc/ssl/metermd/redis-client.crt')),
#     key: OpenSSL::PKey::RSA.new(File.read('/etc/ssl/metermd/redis-client.keydh')),
#   }
# )

set -e

# FIXME: redis-client group
sudo cp files/redis-client.crt /etc/ssl/metermd
sudo cp files/redis-client.dhparam /etc/ssl/metermd
sudo cp files/redis-client.key /etc/ssl/metermd
sudo cp files/redis-client.keydh /etc/ssl/metermd
