#!/usr/bin/env bash

# This works with the following client:
# redis = Redis.new(
#   url: 'rediss://somehost/',
#   ssl_params: {
#     ca_file: '/etc/ssl/metermd/metermd-ca.crt',
#     cert: OpenSSL::X509::Certificate.new(File.read('/etc/ssl/metermd/redis-client.pem')),
#   }
# )

set -e
sudo cp files/redis-client.pem /etc/ssl/metermd
