#!/usr/bin/env bash
set -e

for i in files/*.{crt,key} ; do
  [ -f "/etc/ssl/metermd/$(basename "$i")" ] || sudo cp "$i" /etc/ssl/metermd/
done

sudo chown root:ssl-cert /etc/ssl/metermd/postgres-server.{crt,key}
sudo chmod ug=r,o= /etc/ssl/metermd/postgres-server.key
sudo gpasswd -a cult ssl-cert || true
