#!/usr/bin/env bash
set -e

# NOTE: This must stay somewhat synchonized with the pg_hba.conf in
# postgres-server

PPETC="/etc/pgpool2"

cat - <<PP_HBA | sudo tee -a "$PPETC/pool_hba.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
#
# pgpool doesn't support "hostssl" or "cert clientcert=1 map=cert" via pg_ident.
# We generate this anyway, but pool_hba support is disabled in pgpool.conf
# for now.
#
# hostssl  all          all          255.255.255.255/0  cert clientcert=1 map=cert
# hostssl  all          all          ::1/0              cert clientcert=1 map=cert
PP_HBA

# Comment out any SSL settings and backend settings
sudo sed -r -i.bak -e 's/^(ssl|backend|port|listen_addresses)/#\1/;' "$PPETC/pgpool.conf"

cat - <<PG_CONF | sudo tee -a "$PPETC/pgpool.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
# Empty string means we only accept on the Unix socket.  Port still determines
# the local socket filename, so changing it will require modification to stunnel
# configuration.
listen_addresses = ''
port = 5433
max_connections = 1

ssl = false
PG_CONF

cat - <<EOF | sudo tee "$PPETC/dynamic.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
# This file should be replaced on sync with an actual configuration
EOF
