#!/usr/bin/env bash
set -e

# NOTE: This must stay somewhat synchonized with the pg_hba.conf in
# postgres-server

PPETC="/etc/pgpool2"

# Comment out any SSL settings and backend settings
sudo sed -r -i.bak -e 's/^(ssl|backend|port|listen_addresses)/#\1/;' "$PPETC/pgpool.conf"

cat - <<PG_CONF | sudo tee -a "$PPETC/pgpool.conf"
# <%= cultsrcid %>
# Empty string means we only accept on the Unix socket.  Port still determines
# the local socket filename, so changing it will require modification to stunnel
# configuration.
listen_addresses = ''
port = 5433
max_connections = 1

ssl = false
PG_CONF

cat - <<EOF | sudo tee "$PPETC/dynamic.conf"
# <%= cultsrcid %>
# This file should be replaced on sync with an actual configuration
EOF
