#!/usr/bin/env bash
set -e

<%
  servers = node.zone_peers.with(role: 'postgres-server').sort_by do |server|
    server.zone_leader?('postgres-server') ? 0 : 1
  end
%>

PPETC="/etc/pgpool2"

cat - <<DYNAMIC_CONF | sudo tee "$PPETC/dynamic.conf"
# GENERATED IN CULT PROJECT: <%= __FILE__ %>
load_balance_mode = on
master_slave_mode = on
master_slave_sub_mode = 'stream'

<% servers.each.with_index do |server, i| %>
# Upstream Server: <%= server.name %>
backend_hostname<%= i %> = '/var/run/stunnel@pgpool-out/<%=server.name %>/'
backend_port<%= i %> = 5432
backend_weight<%= i %> = 1
# backend_data_directory<%= i %> = '/var/lib/pgsql/data'
backend_flag<%= i %> = 'ALLOW_TO_FAILOVER'

<% end %>
DYNAMIC_CONF
