#!/bin/sh
set -e

# We make sure this node has a valid hostname.  Different VPS providers handle
# this differently, and sudo will be weird if it can't resolve its hostname.

NODE_NAME=<%= node.name.e %>

echo "$NODE_NAME" > /etc/hostname
hostname "$NODE_NAME"

# read /etc/hosts in a canonical format: Comments removed, whitespace
# collapsed, and return the hostnames.
HOSTS=$(cat /etc/hosts | sed -e 's/#.*//g' \
                       | sed -e 's/\t/ /g' \
                       | tr -s ' ' \
                       | grep -v '^\s*$' \
                       | cut -d ' ' -f2-)

# See if we're in hosts
if ! echo "$HOSTS" | grep -E -q "\b$NODE_NAME\b" ; then
  echo "127.0.1.1 $NODE_NAME" >> /etc/hosts
  echo "::1 $NODE_NAME" >> /etc/hosts
fi

# Make the SSH experience a little nicer with the full hostname in the prompt
echo "export PS1='\u@\H:\w\$ '" >> /etc/bash.bashrc
