#!/bin/sh
set -e

# We move root's authorized_keys to a new 'cult' user, disable the root account,
# and give 'cult' sudo superpowers.

adduser --disabled-password --gecos 'Cult Deployment Account' cult

mkdir -p /home/cult/.ssh
mv "$HOME/.ssh/authorized_keys" /home/cult/.ssh
chown -R cult:cult /home/cult/.ssh
chmod -R 0700 /home/cult/.ssh
chmod -R 0600 /home/cult/.ssh/*

echo 'cult ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cult-nopasswd

# disable root account
passwd -l root
sed -i.bak -e 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

systemctl reload sshd
