#!/usr/bin/env bash
set -e

if [ -d "/etc/update-motd.d" ]; then
  cp "files/cult-motd" "/etc/update-motd.d/99-cult-motd"
  chmod +x "/etc/update-motd.d/99-cult-motd"
elif [ -f "/etc/motd" ]; then
  ./files/cult-motd >> "/etc/motd"
fi
