#!/usr/bin/env bash
set -e

sudo ufw-delete-by-comment 'postgres-common:'

<% node.zone_peers.with(role: 'postgres-server').each do |other| %>
  sudo ufw allow out to <%= other.addr_from(node).q %> \
                     port 5432 \
                     from <%= node.addr_from(other).q %> \
                     comment 'postgres-common: accessing <%= other.name.q %>'
<% end %>
