#!/usr/bin/env bash

sudo cp files/stunnel/redis-server.conf /etc/stunnel

sudo cp files/redis-server.crt /etc/stunnel/certs
sudo cp files/redis-server.key /etc/stunnel/keys

sudo chown redis:redis /etc/stunnel/keys/redis-server.key
sudo chmod u=rw,go= /etc/stunnel/keys/redis-server.key
